# Generated by Django 4.1.5 on 2023-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('F', 'For adoption'), ('A', 'Adopted')], default='F', max_length=1),
        ),
    ]
