# Generated by Django 4.1.5 on 2023-01-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestadoption',
            old_name='data',
            new_name='date',
        ),
    ]
